# Generated by Django 5.1.6 on 2025-02-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoMovimentacao',
        ),
    ]
