# Generated by Django 5.1.6 on 2025-02-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_delete_alunomovimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='aluno',
        ),
    ]
