# Generated by Django 5.1.6 on 2025-02-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_remove_item_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='professor',
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
